---

- name: Partition disk
  parted:
    device: /dev/xvdf
    number: 1
    state: present

- name: Create Filesystem on parition
  filesystem:
    fstype: xfs
    dev: /dev/xvdf1

- name: Mount data disk for /opt/apache
  mount:
    path: /opt/apache
    src: /dev/xvdf1
    fstype: xfs
    state: mounted
