---

- name: Partition disk
  parted:
    device: /dev/nvme1n1
    number: 1
    state: present

- name: Create Filesystem on parition
  filesystem:
    fstype: xfs
    dev: /dev/nvme1n1p1

- name: Mount data disk for /opt/apache
  mount:
    path: /opt/apache
    src: /dev/nvme1n1p1
    fstype: xfs
    state: mounted
