# .bashrc

## Manage by Ansible ##

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

AWS_HOSTNAME=$(curl -s http://169.254.169.254/latest/meta-data/tags/instance/Name)
PS1='\[\e[0m\]\d \[\e[0m\]\t \[\e[0m\]$AWS_HOSTNAME\[\e[0m\]:\[\e[0m\]\w\[\e[0m\]:> '

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions