---

- name: Playbook ssh disable task
  hosts: localhost
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Disable sshd service
      service:
        name: sshd
        enabled: no