---

- name: Playbook ssh enable task
  hosts: localhost
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Enable sshd service
      service:
        name: sshd
        enabled: yes