---

- name: Playbook to call Apache Server role
  hosts: localhost
  become: yes
  become_user: root
  gather_facts: yes

  tasks:
    - name: Example command 1
      shell:  uname -a > file-uname.out

    - name: Example command 2
      shell: whoami

    - name: Example command 3
      shell:  systemctl restart sshd.service