# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-template-ec2-lz-nonprod-ap-southeast-2.state"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "ap-southeast-2/dev/parameters/terraform.tfstate"
    region         = "ap-southeast-2"
  }
}
