# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "ap-southeast-2"
   default_tags {
    tags = {
     "uts:application"    = "ec2"
     "uts:project"        = "template"
     "uts:costcentre"     = "905010.70410"
     "uts:env"            = "dev"
     "uts:primarycontact" = "ultan.lankford@uts.edu.au"
   }
 }
  allowed_account_ids = ["609576312521"]
  assume_role {
    role_arn     = "arn:aws:iam::609576312521:role/nonprod_devsecops_cross_account_role"
    session_name = "SESSION_NAME"
    external_id  = "EXTERNAL_ID"
  }
}
