name: 'Terragrunt GitHub Actions'

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  tf_version: 'latest'
  tg_version: 'latest'

jobs:
  dev:
    name: 'Terragrunt apply dev'
    runs-on: ubuntu-latest
    environment: dev
    steps:
    
      - name: 'checkout'
        uses: actions/checkout@master

      - name: 'Terragrunt run-all apply'
        uses: maniankara/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_binary: 'terragrunt'
          tf_actions_subcommand: 'run-all apply'
          tf_actions_working_dir: 'ap-southeast-2/dev'
        env:
          AWS_DEFAULT_REGION: 'ap-southeast-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          TF_INPUT: false
