name: Disable SSH

on:
  workflow_dispatch:

jobs:

  dev:
    name: 'Disable SSH'
    runs-on: ubuntu-latest
    environment: dev
    steps:

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SIT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SIT_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Run Association to Disable ssh service
        run: |
          aws ssm start-associations-once --association-id "01edc9d4-63d6-47fc-ab42-cdb5307f1c08"