name: Enable SSH

on:
  workflow_dispatch:

jobs:

  dev:
    name: 'Enable SSH'
    runs-on: ubuntu-latest
    environment: dev
    steps:

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SIT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SIT_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Run Association to Enable ssh service
        run: |
          aws ssm start-associations-once --association-id "e87e602b-2b08-44d7-b3c9-247825c24b16"