name: Prisma CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_for_prisma:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}
      - name: List root dir of container
        run: |
          ls -lah /
      - name: Prisma config scan
        uses: uts-itd/actions.public.prismaconfig@latest